export type MediaType = "anime" | "manga";
export type MediaRelation = { relation: string; id: number; mediaType: MediaType; title: string };
export type MediaLink = { name: string; url: string };
export type MediaSummary = { id: number; mediaType: MediaType; title: string; originalTitle?: string; imageUrl: string; malUrl: string; synopsis?: string; format?: string; status?: string; score?: number; year?: number; progressTotal?: number; secondaryTotal?: number; genres: string[]; themes: string[] };
export type MediaDetails = MediaSummary & {
  approved?: boolean;
  titleSynonyms?: string[];
  source?: string;
  scoredBy?: number;
  background?: string;
  season?: string;
  broadcast?: string;
  rating?: string;
  duration?: string;
  trailerUrl?: string;
  dateRange?: string;
  rank?: number;
  popularity?: number;
  members?: number;
  favourites?: number;
  studios: string[];
  creators: string[];
  licensors?: string[];
  demographics?: string[];
  explicitGenres?: string[];
  serializations?: string[];
  openings?: string[];
  endings?: string[];
  externalLinks?: MediaLink[];
  streamingLinks?: MediaLink[];
  relations?: MediaRelation[];
  genreRefs?: GenreRef[];
  themeRefs?: GenreRef[];
  demographicRefs?: GenreRef[];
};
export type MediaVoiceActor = { name: string; imageUrl?: string; language: string };
export type MediaCharacter = { id: number; name: string; imageUrl?: string; role?: string; favorites?: number; voiceActor?: MediaVoiceActor };
export type MediaStaff = { id: number; name: string; imageUrl?: string; positions: string[] };
export type MediaPicture = { small?: string; large: string };
export type GenreRef = { id: number; name: string };
export type PaginatedMedia = { items: MediaSummary[]; page: number; hasNextPage: boolean; total?: number; source?: "jikan" | "kitsu" };
export type SearchMediaInput = { mediaType: MediaType; query?: string; page?: number; genre?: number; status?: string; orderBy?: "score" | "popularity" | "start_date"; sort?: "asc" | "desc" };
