import { ArrowRight, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SelectMenu } from "@/components/ui/select-menu";
import { genreOptions, statusOptions } from "@/features/catalog/filters";
import type { MediaType } from "@/features/catalog/model";

export function SearchFilters({ mediaType = "anime", query = "", sort = "popularity", genre = "", status = "" }: { mediaType?: MediaType; query?: string; sort?: string; genre?: string; status?: string }) {
  return <form action="/discover" className="grid gap-3 rounded-3xl border border-white/8 bg-white/[.035] p-3 md:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_120px_150px_150px_160px_auto]" method="get" role="search"><label className="relative"><span className="sr-only">Search titles</span><Search aria-hidden="true" className="pointer-events-none absolute left-4 top-3.5 text-zinc-500" size={17} /><Input className="pl-11" defaultValue={query} name="q" placeholder="Search titles, worlds, stories..." type="search" /></label><SelectMenu ariaLabel="Media type" defaultValue={mediaType} name="type" options={[{ value: "anime", label: "Anime" }, { value: "manga", label: "Manga" }]} /><SelectMenu ariaLabel="Genre" defaultValue={genre} name="genre" options={[{ value: "", label: "All genres" }, ...genreOptions]} /><SelectMenu ariaLabel="Status" defaultValue={status} name="status" options={[{ value: "", label: "Any status" }, ...statusOptions(mediaType)]} /><SelectMenu ariaLabel="Sort by" defaultValue={sort} name="sort" options={[{ value: "popularity", label: "Most popular" }, { value: "score", label: "Highest rated" }, { value: "newest", label: "Newest first" }]} /><Button className="min-w-[10.5rem] whitespace-nowrap border border-violet-300/30 bg-violet-500 px-5 text-oncover shadow-[0_10px_26px_-15px_rgba(139,92,246,.85)] hover:bg-violet-400 focus-visible:ring-violet-300 xl:w-auto" type="submit"><span>Show results</span><ArrowRight aria-hidden="true" size={17} /></Button></form>;
}
